version: '3'

networks:
  network:
    name: network_${APP_NAME}

services:
  php:
    build:
      context: ./configs
      dockerfile: php.dockerfile
      args:
        - PUID=${PUID:-1000}
        - PGID=${PGID:-1000}
    container_name: ${APP_NAME}_php
    volumes:
      - ./${APP_NAME}:/var/www/html:delegated
    networks:
      - network

  mysql:
    image: yobasystems/alpine-mariadb:10
    container_name: ${APP_NAME}_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_NAME: mysql
    networks:
      - network

  nginx:
    build:
      context: ./configs
      dockerfile: nginx.dockerfile
      args:
        - PUID=${PUID:-1000}
        - PGID=${PGID:-1000}
    container_name: ${APP_NAME}_nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./${APP_NAME}:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - network

  composer:
    build:
      context: ./configs
      dockerfile: composer.dockerfile
      args:
        - PUID=${PUID:-1000}
        - PGID=${PGID:-1000}
    container_name: ${APP_NAME}_composer
    volumes:
      - ./${APP_NAME}:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - network

  npm:
    image: node:17.4
    container_name: ${APP_NAME}_npm
    volumes:
      - ./${APP_NAME}:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - network

  artisan:
    build:
      context: ./configs
      dockerfile: php.dockerfile
      args:
        - PUID=${PUID:-1000}
        - PGID=${PGID:-1000}
    container_name: ${APP_NAME}_artisan
    volumes:
      - ./${APP_NAME}:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - network
